### ISSUE TITLE
Config options do not work

### ISSUE THREAD

**Issue by jacobeva** [martineausimon/nvim-mail-merge#2]
Hi, first I'd just like to thank you for releasing this plugin publicly, it's been a huge help to me :)

I thought I'd mention something though. The options array doesn't seem to work, as changing any of the options in my packer configuration doesn't seem to work. For example, I started off by trying to change the "neomutt_config" variable in order to point to my neomuttrc file generated by mutt_wizard, but noticed that the mail merge wasn't working.
On further inspection, I realised that the plugin was still using the default directory, "$HOME/.neomuttrc". Hell, I even changed the defaults in the lua source code and for some reason it still used the wrong directory. In the end, I had to hardcode the path in [this file](https://github.com/martineausimon/nvim-mail-merge/blob/main/lua/nvmm.lua#L239).

Any ideas why this happens? It's the same for other options too.

**Comment by martineausimon** [comment]
Hi, thanks for your feedback, and sorry for this issue !
It should work though... Can I ask you if you have launched "PackerCompile" after having done the configuration?

**Comment by jacobeva** [comment]
Oooh no I didn't, let me try that.

**Comment by jacobeva** [comment]
That was exactly the case, so sorry! I don't have very much experience with lua I'm afraid. Thanks for the help!
